# Generated by Django 4.2.7 on 2025-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_enquiry_data_link_enquiry_data_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=150)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('fresher', models.BooleanField(default=False)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('relevant_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('highest_degree', models.CharField(blank=True, max_length=150, null=True)),
                ('college', models.CharField(blank=True, max_length=150, null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
                ('currently_working', models.CharField(blank=True, max_length=10, null=True)),
                ('notice_period', models.IntegerField(blank=True, null=True)),
                ('current_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_ctc', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('details_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
