# Generated by Django 4.2.7 on 2025-11-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_studentplacement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentplacement',
            old_name='details_done',
            new_name='edu_ongoing',
        ),
        migrations.RemoveField(
            model_name='studentplacement',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='studentplacement',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='studentplacement',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='studentplacement',
            name='preferred_location',
        ),
        migrations.RemoveField(
            model_name='studentplacement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='edu_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='edu_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='edu_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='high_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='high_school_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='high_school_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='high_school_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='high_school_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='location_current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='location_preferred',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='pre_uni_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='pre_uni_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='pre_uni_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='pre_uni_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='pre_uni_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='highest_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='notice_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='relevant_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentplacement',
            name='total_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.studentplacement')),
            ],
        ),
    ]
