# Generated by Django 4.2.7 on 2025-11-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_details_done_studentplacement_edu_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplacement',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.enquiry'),
        ),
    ]
